signal_generation:
  srate: 250          # Sampling rate in Hz
  duration: 6         # Seconds per trial
  n_trials: 20        # Total trials
  channels: ['C3', 'C4'] # C3 (Left Motor Cortex), C4 (Right Motor Cortex)

freq_bands:
  Delta: [0.5, 4]
  Theta: [4, 8]
  Alpha: [8, 13]
  Beta: [13, 30]
  Gamma: [30, 80]